### PR TITLE
fix(newListing): Validate price upper bound with explicit error

### LINKED ISSUE #291: Fix price field (bug when above 200.-)
Listing type does not accept prive above 200
don't handle it silently make a error msg

### PR DESCRIPTION
**Pull request by nikitaKrpch**
# What I did
Fixed the price validation logic so listings with a price above **200.-** are rejected with a clear error message instead of failing silently.

# How I did it
- Added a `maxPrice` limit and a corresponding error message  
- Updated `setPrice()` and `setError()` to detect and flag prices > 200  
- Ensured `invalidPriceMsg` triggers UI error highlighting and blocks submission

# How to verify it
1. Open the **New Listing** screen  
2. Enter a price **greater than 200**  
3. Confirm that an error message appears and the listing cannot be submitted

# Demo video
https://github.com/user-attachments/assets/ca29092e-be63-41aa-b398-4356c032eb40

# Pre-merge checklist
The changes I introduced:
- [x] work correctly  
- [x] do not break other functionalities  
- [x] work correctly on Android  
- [x] are fully tested (or have tests added)

### CODE REVIEW

File: app/src/main/java/com/android/sample/ui/newListing/NewListingViewModel.kt [hunk 1]
```diff
@@ -105,6 +105,9 @@ class NewListingViewModel(
   private var locationSearchJob: Job? = null
   private val locationSearchDelayTime: Long = 1000
 
+  private val maxPrice = 200.0
```
Comment (nahuelArthur) [inline app/src/main/java/com/android/sample/ui/newListing/NewListingViewModel.kt]: Shouldn't be hardcoded here I think. Maybe crate a public const val in FirestoreListingRepository to get the max value, so if this max value your code is still coherent. Not mandatory but can be good.

**Review by nahuelArthur — CHANGES_REQUESTED** [review]
Good implementation, coherent with the error msg system of this viewModel.
Maybe a small change to keep your code coherent with the max price value, if that value changes

**Review by nahuelArthur — APPROVED** [review]
lgtm
